name: miscelaneos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_compass: ^0.7.0
  flutter_riverpod: ^2.3.6
  geolocator: ^9.0.2
  go_router: ^8.0.3
  google_fonts: ^5.0.0
  google_maps_flutter: ^2.3.1
  local_auth: ^2.1.6
  permission_handler: ^10.3.0
  quick_actions: ^1.0.5
  sensors_plus: ^3.0.2
  share_plus: ^7.0.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
